/**
 * 25 realistic Indian + international scholarships seed data
 * Run: node scripts/seed.js
 */
const scholarships = [
  // ── GOVERNMENT / INDIA ──────────────────────────────────────────────────────
  {
    name: "National Scholarship Portal (NSP) — Post-Matric",
    provider: "Ministry of Education, India",
    amount_value: 120000,
    amount_currency: "INR",
    amount_string: "₹1.2 lakh/year",
    cover_type: "partial",
    cover_details: "Tuition fee reimbursement + maintenance allowance",
    education_level: "undergrad",
    field_of_study: ["All"],
    country: "India",
    study_location: "India",
    max_income_annual: 250000,
    min_gpa: 50,
    requires_disability: false,
    citizenship: "Indian",
    min_work_experience: 0,
    required_gender: "Any",
    deadline: "2027-11-30",
    application_url: "https://scholarships.gov.in",
    required_documents: ["10th Marksheet", "12th Marksheet", "Income Certificate", "Aadhaar Card", "Bank Passbook", "Caste Certificate (if applicable)", "Current Year Admission Proof"],
    application_effort_hours: 4,
    application_method: "Online",
    selection_criteria: "Merit-cum-means",
    provider_type: "government",
    provider_website: "https://scholarships.gov.in",
    awards_per_year: 50000,
    verified: true,
    notes: "Largest scholarship scheme in India. Apply before October each year.",
  },
  {
    name: "Prime Minister's Scholarship Scheme (PMSS)",
    provider: "Ministry of Home Affairs, India",
    amount_value: 36000,
    amount_currency: "INR",
    amount_string: "₹3,000/month (₹36,000/year)",
    cover_type: "partial",
    cover_details: "Monthly stipend for wards of ex-servicemen",
    education_level: "undergrad",
    field_of_study: ["Engineering", "Medicine", "Business", "Law", "Computer Science", "All"],
    country: "India",
    study_location: "India",
    max_income_annual: null,
    min_gpa: 60,
    requires_disability: false,
    citizenship: "Indian",
    min_work_experience: 0,
    required_gender: "Any",
    deadline: "2027-10-31",
    application_url: "https://ksb.gov.in/pmss.htm",
    required_documents: ["10th & 12th Marksheet", "Ex-serviceman Certificate", "Aadhaar Card", "Bank Account Details", "Admission Letter"],
    application_effort_hours: 5,
    application_method: "Online",
    selection_criteria: "Merit-based",
    provider_type: "government",
    awards_per_year: 5500,
    verified: true,
    notes: "For children and widows of ex-servicemen/ex-coast guard. ₹3,000/month for boys, ₹3,500/month for girls.",
  },
  {
    name: "INSPIRE Scholarship (SHE)",
    provider: "Department of Science & Technology, India",
    amount_value: 80000,
    amount_currency: "INR",
    amount_string: "₹80,000/year",
    cover_type: "partial",
    cover_details: "Annual scholarship + summer attachment grant",
    education_level: "undergrad",
    field_of_study: ["Science", "Computer Science", "Engineering"],
    country: "India",
    study_location: "India",
    max_income_annual: null,
    min_gpa: 80,
    requires_disability: false,
    citizenship: "Indian",
    min_work_experience: 0,
    required_gender: "Any",
    deadline: "2027-10-15",
    application_url: "https://online-inspire.gov.in",
    required_documents: ["12th Marksheet (top 1% proof)", "Admission Letter (BSc/BS/Int. MSc)", "Aadhaar Card", "Bank Details"],
    application_effort_hours: 4,
    application_method: "Online",
    selection_criteria: "Top 1% in Class 12 board exams",
    provider_type: "government",
    awards_per_year: 10000,
    competitive_ratio: "1:10",
    verified: true,
    notes: "Must be in top 1% of Class 12 and pursuing BSc/Int. MSc in natural/basic sciences.",
  },
  {
    name: "AICTE Pragati Scholarship for Girls",
    provider: "AICTE (All India Council for Technical Education)",
    amount_value: 50000,
    amount_currency: "INR",
    amount_string: "₹50,000/year + contingency",
    cover_type: "partial",
    cover_details: "Tuition fee + contingency grant of ₹2,000",
    education_level: "undergrad",
    field_of_study: ["Engineering", "Computer Science"],
    country: "India",
    study_location: "India",
    max_income_annual: 800000,
    min_gpa: 0,
    requires_disability: false,
    citizenship: "Indian",
    min_work_experience: 0,
    required_gender: "Female",
    deadline: "2027-11-15",
    application_url: "https://www.aicte-india.org/bureaus/boys_girls",
    required_documents: ["10th & 12th Marksheet", "Income Certificate", "Aadhaar Card", "Admission Letter", "Bank Passbook", "Self-declaration Form"],
    application_effort_hours: 4,
    application_method: "Online",
    selection_criteria: "Need-based + Merit",
    provider_type: "government",
    awards_per_year: 4000,
    competitive_ratio: "1:5",
    verified: true,
    notes: "For girls in AICTE-approved technical institutions. One girl per family.",
  },
  {
    name: "AICTE Saksham Scholarship for Specially Abled",
    provider: "AICTE",
    amount_value: 50000,
    amount_currency: "INR",
    amount_string: "₹50,000/year",
    cover_type: "partial",
    cover_details: "Tuition fee reimbursement + contingency allowance",
    education_level: "undergrad",
    field_of_study: ["Engineering", "Computer Science"],
    country: "India",
    study_location: "India",
    max_income_annual: 800000,
    min_gpa: 0,
    requires_disability: true,
    citizenship: "Indian",
    min_work_experience: 0,
    required_gender: "Any",
    deadline: "2027-11-15",
    application_url: "https://www.aicte-india.org",
    required_documents: ["Disability Certificate (≥40%)", "Income Certificate", "Aadhaar", "Admission Letter", "Marksheets"],
    application_effort_hours: 4,
    provider_type: "government",
    awards_per_year: 1000,
    verified: true,
    notes: "For students with ≥40% disability in AICTE-approved programmes.",
  },
  {
    name: "Central Sector Scheme (CSS) Scholarship",
    provider: "Ministry of Education, India",
    amount_value: 20000,
    amount_currency: "INR",
    amount_string: "₹10,000–20,000/year",
    cover_type: "partial",
    cover_details: "Annual scholarship for meritorious students from non-elite families",
    education_level: "undergrad",
    field_of_study: ["All"],
    country: "India",
    study_location: "India",
    max_income_annual: 450000,
    min_gpa: 80,
    requires_disability: false,
    citizenship: "Indian",
    min_work_experience: 0,
    required_gender: "Any",
    deadline: "2027-10-31",
    application_url: "https://scholarships.gov.in",
    required_documents: ["12th Marksheet", "Income Certificate", "Aadhaar", "Admission Letter", "Bank Details"],
    application_effort_hours: 3,
    provider_type: "government",
    awards_per_year: 82000,
    competitive_ratio: "1:3",
    verified: true,
    notes: "80,000+ awards per year. Among the most accessible central scholarships.",
  },
  // ── INTERNATIONAL ───────────────────────────────────────────────────────────
  {
    name: "Fulbright-Nehru Master's Fellowship",
    provider: "United States-India Educational Foundation (USIEF)",
    amount_value: 5000000,
    amount_currency: "INR",
    amount_string: "Full funding (~$50,000/year)",
    cover_type: "full",
    cover_details: "J-1 visa, tuition, living stipend, health insurance, travel",
    education_level: "postgrad",
    field_of_study: ["All"],
    country: "USA",
    study_location: "Abroad",
    max_income_annual: null,
    min_gpa: 65,
    requires_disability: false,
    citizenship: "Indian",
    min_work_experience: 2,
    required_gender: "Any",
    deadline: "2027-07-15",
    application_url: "https://www.usief.org.in/Fellowships/Fulbright-Nehru-Master-Fellowships.aspx",
    required_documents: ["Statement of Purpose (2000 words)", "3 Reference Letters", "Transcripts", "CV/Resume", "GRE/GMAT Score (optional)", "IELTS/TOEFL Score", "Passport"],
    application_effort_hours: 40,
    application_method: "Online",
    selection_criteria: "Merit-based + Leadership",
    provider_type: "international",
    competitive_ratio: "1:100",
    awards_per_year: 85,
    verified: true,
    notes: "Prestigious fully-funded scholarship for Master's at top US universities. 2+ years work experience required.",
  },
  {
    name: "Commonwealth Scholarship (UK)",
    provider: "Commonwealth Scholarship Commission (CSC)",
    amount_value: 6000000,
    amount_currency: "INR",
    amount_string: "Full funding (~£45,000)",
    cover_type: "full",
    cover_details: "Tuition, living allowance, airfare, thesis grant, study travel",
    education_level: "postgrad",
    field_of_study: ["All"],
    country: "UK",
    study_location: "Abroad",
    max_income_annual: null,
    min_gpa: 70,
    requires_disability: false,
    citizenship: "Indian",
    min_work_experience: 0,
    required_gender: "Any",
    deadline: "2027-10-31",
    application_url: "https://cscuk.fcdo.gov.uk/apply/scholarships/",
    required_documents: ["Research Proposal", "3 Academic References", "Transcripts", "CV", "IELTS (6.5+)", "Passport"],
    application_effort_hours: 35,
    selection_criteria: "Merit + Development impact",
    provider_type: "international",
    competitive_ratio: "1:150",
    awards_per_year: 30,
    verified: true,
    notes: "For Master's and PhD. Must demonstrate how you'll contribute to India's development.",
  },
  {
    name: "DAAD Scholarship (Germany)",
    provider: "German Academic Exchange Service (DAAD)",
    amount_value: 1200000,
    amount_currency: "INR",
    amount_string: "€934/month + travel + health insurance",
    cover_type: "full",
    cover_details: "Monthly stipend, travel allowance, health/accident/liability insurance",
    education_level: "postgrad",
    field_of_study: ["Engineering", "Computer Science", "Science", "All"],
    country: "Germany",
    study_location: "Abroad",
    max_income_annual: null,
    min_gpa: 70,
    requires_disability: false,
    citizenship: "Indian",
    min_work_experience: 2,
    required_gender: "Any",
    deadline: "2027-10-15",
    application_url: "https://www.daad.in/en/find-funding/",
    required_documents: ["Motivation Letter", "CV", "2 Reference Letters", "Transcripts", "German/English Language Certificate", "Research Proposal (for PhD)"],
    application_effort_hours: 20,
    selection_criteria: "Academic excellence + motivation",
    provider_type: "international",
    competitive_ratio: "1:50",
    awards_per_year: 200,
    verified: true,
    notes: "Multiple programmes. Many German universities have no tuition fees.",
  },
  {
    name: "Australia Awards Scholarship",
    provider: "Australian Government — DFAT",
    amount_value: 7500000,
    amount_currency: "INR",
    amount_string: "Full funding (AUD 80,000+/year)",
    cover_type: "full",
    cover_details: "Tuition, living allowance, health insurance, return airfare, introductory academic programme",
    education_level: "postgrad",
    field_of_study: ["All"],
    country: "Australia",
    study_location: "Abroad",
    max_income_annual: null,
    min_gpa: 65,
    requires_disability: false,
    citizenship: "Indian",
    min_work_experience: 2,
    required_gender: "Any",
    deadline: "2027-06-30",
    application_url: "https://www.australiaawards.gov.au/",
    required_documents: ["Personal Statement", "2 Professional References", "Transcripts", "IELTS (6.5+)", "CV", "Passport"],
    application_effort_hours: 25,
    selection_criteria: "Academic + Development impact",
    provider_type: "international",
    competitive_ratio: "1:80",
    awards_per_year: 50,
    verified: true,
    notes: "Prestigious scholarship for Master's at top Australian universities. Return to home country required after study.",
  },
  {
    name: "Erasmus Mundus Joint Master's",
    provider: "European Commission",
    amount_value: 4800000,
    amount_currency: "INR",
    amount_string: "€1,400/month + travel + tuition waiver",
    cover_type: "full",
    cover_details: "Monthly living allowance, travel grant, installation costs, tuition fee waiver",
    education_level: "postgrad",
    field_of_study: ["Computer Science", "Engineering", "Science", "Data Science", "All"],
    country: "Europe",
    study_location: "Abroad",
    max_income_annual: null,
    min_gpa: 70,
    requires_disability: false,
    citizenship: "Any",
    min_work_experience: 0,
    required_gender: "Any",
    deadline: "2027-01-15",
    application_url: "https://www.eacea.ec.europa.eu/scholarships/emjmd-catalogue",
    required_documents: ["Motivation Letter", "CV (Europass)", "2 Academic References", "Transcripts", "IELTS/TOEFL", "Language Certificates"],
    application_effort_hours: 25,
    selection_criteria: "Academic excellence",
    provider_type: "international",
    competitive_ratio: "1:60",
    awards_per_year: 2000,
    verified: true,
    notes: "Study in 2–3 European countries. Highly prestigious. Many programmes in English.",
  },
  {
    name: "Inlaks Scholarships",
    provider: "Inlaks Shivdasani Foundation",
    amount_value: 10000000,
    amount_currency: "INR",
    amount_string: "Up to $100,000 (for USA/UK/Europe)",
    cover_type: "full",
    cover_details: "Tuition, living expenses, economy airfare",
    education_level: "postgrad",
    field_of_study: ["All"],
    country: "USA",
    study_location: "Abroad",
    max_income_annual: null,
    min_gpa: 70,
    requires_disability: false,
    citizenship: "Indian",
    min_work_experience: 0,
    required_gender: "Any",
    deadline: "2027-03-31",
    application_url: "https://www.inlaksfoundation.org/scholarships/",
    required_documents: ["Personal Statement (1000 words)", "CV", "2 Referees", "Transcripts", "Proof of Admission to top university", "Passport"],
    application_effort_hours: 20,
    selection_criteria: "Academic + Leadership + India impact",
    provider_type: "ngo",
    competitive_ratio: "1:200",
    awards_per_year: 20,
    verified: true,
    notes: "Must have unconditional offer from top 50 university worldwide. Highly competitive.",
  },
  // ── CORPORATE / NGO ─────────────────────────────────────────────────────────
  {
    name: "Tata Scholarship — Cornell University",
    provider: "Tata Education and Development Trust",
    amount_value: 5800000,
    amount_currency: "INR",
    amount_string: "Full funding at Cornell (~$70,000/year)",
    cover_type: "full",
    cover_details: "Full tuition, living expenses, health insurance, books",
    education_level: "undergrad",
    field_of_study: ["All"],
    country: "USA",
    study_location: "Abroad",
    max_income_annual: 5000000,
    min_gpa: 90,
    requires_disability: false,
    citizenship: "Indian",
    min_work_experience: 0,
    required_gender: "Any",
    deadline: "2027-01-02",
    application_url: "https://financialaid.cornell.edu/types-aid/scholarships/tata-scholarship/",
    required_documents: ["Cornell Application", "Financial Aid Application (CSS Profile)", "10th & 12th Marksheets", "Letter of Recommendation (3)", "Essays", "SAT/ACT Score"],
    application_effort_hours: 50,
    selection_criteria: "Merit + Need",
    provider_type: "corporate",
    competitive_ratio: "1:500",
    awards_per_year: 20,
    verified: true,
    notes: "One of the most prestigious awards for Indian students at Cornell. Need-based with merit consideration.",
  },
  {
    name: "Reliance Foundation Scholarships",
    provider: "Reliance Foundation",
    amount_value: 600000,
    amount_currency: "INR",
    amount_string: "₹6 lakh total (₹2L/year for 3 years)",
    cover_type: "partial",
    cover_details: "Annual merit scholarship for undergraduate students",
    education_level: "undergrad",
    field_of_study: ["Engineering", "Computer Science", "Science", "Business"],
    country: "India",
    study_location: "India",
    max_income_annual: 1500000,
    min_gpa: 60,
    requires_disability: false,
    citizenship: "Indian",
    min_work_experience: 0,
    required_gender: "Any",
    deadline: "2027-04-30",
    application_url: "https://www.reliancefoundation.org/",
    required_documents: ["10th & 12th Marksheet", "Income Certificate", "Aadhaar", "Admission Letter", "Essay (500 words on social impact)"],
    application_effort_hours: 8,
    selection_criteria: "Merit + Need + Social impact potential",
    provider_type: "corporate",
    competitive_ratio: "1:30",
    awards_per_year: 5000,
    verified: true,
    notes: "Includes mentorship from Reliance professionals.",
  },
  {
    name: "Wipro Cares Scholarship",
    provider: "Wipro Foundation",
    amount_value: 150000,
    amount_currency: "INR",
    amount_string: "₹1.5 lakh/year",
    cover_type: "partial",
    cover_details: "Annual merit-cum-means scholarship for engineering students",
    education_level: "undergrad",
    field_of_study: ["Engineering", "Computer Science"],
    country: "India",
    study_location: "India",
    max_income_annual: 600000,
    min_gpa: 70,
    requires_disability: false,
    citizenship: "Indian",
    min_work_experience: 0,
    required_gender: "Any",
    deadline: "2027-08-31",
    application_url: "https://www.wipro.com/sustainability/wipro-cares/",
    required_documents: ["10th & 12th Marksheet", "Income Certificate", "Aadhaar", "College Admission Letter", "Bank Account"],
    application_effort_hours: 5,
    selection_criteria: "Merit + Need",
    provider_type: "corporate",
    competitive_ratio: "1:20",
    awards_per_year: 500,
    verified: true,
  },
  {
    name: "Aga Khan Foundation International Scholarship",
    provider: "Aga Khan Foundation",
    amount_value: 2500000,
    amount_currency: "INR",
    amount_string: "50% grant + 50% loan (~$25,000/year)",
    cover_type: "partial",
    cover_details: "Half grant, half interest-free loan covering tuition and living",
    education_level: "postgrad",
    field_of_study: ["All"],
    country: "USA",
    study_location: "Abroad",
    max_income_annual: 1000000,
    min_gpa: 65,
    requires_disability: false,
    citizenship: "Indian",
    min_work_experience: 2,
    required_gender: "Any",
    deadline: "2027-03-31",
    application_url: "https://www.akdn.org/our-agencies/aga-khan-foundation/social-development/education/higher-education",
    required_documents: ["Letter of Intent", "CV", "2 References", "Transcripts", "Proof of Admission", "Financial documents", "Essay on development goals"],
    application_effort_hours: 20,
    selection_criteria: "Need + Merit + Leadership",
    provider_type: "ngo",
    competitive_ratio: "1:60",
    awards_per_year: 30,
    verified: true,
    notes: "Primarily for students from developing nations pursuing postgrad abroad.",
  },
  {
    name: "Google Generation Scholarship",
    provider: "Google LLC",
    amount_value: 750000,
    amount_currency: "INR",
    amount_string: "$7,500 (~₹6.25 lakh)",
    cover_type: "partial",
    cover_details: "Annual cash scholarship + Google mentorship",
    education_level: "undergrad",
    field_of_study: ["Computer Science", "Data Science", "Engineering"],
    country: "India",
    study_location: "India",
    max_income_annual: null,
    min_gpa: 70,
    requires_disability: false,
    citizenship: "Any",
    min_work_experience: 0,
    required_gender: "Female",
    deadline: "2027-03-01",
    application_url: "https://buildyourfuture.withgoogle.com/scholarships/",
    required_documents: ["CV/Resume", "Transcripts", "Essay (600 words)", "1 Reference Letter"],
    application_effort_hours: 10,
    selection_criteria: "Merit + Demonstrated passion for tech",
    provider_type: "corporate",
    competitive_ratio: "1:100",
    awards_per_year: 30,
    verified: true,
    notes: "For women in Computer Science. Includes Google Summer of Code preference.",
  },
  {
    name: "KVPY Fellowship (Kishore Vaigyanik Protsahan Yojana)",
    provider: "Department of Science & Technology, India",
    amount_value: 96000,
    amount_currency: "INR",
    amount_string: "₹5,000–7,000/month fellowship",
    cover_type: "partial",
    cover_details: "Monthly fellowship during BSc/Int. MSc + annual contingency grant",
    education_level: "undergrad",
    field_of_study: ["Science", "Computer Science"],
    country: "India",
    study_location: "India",
    max_income_annual: null,
    min_gpa: 75,
    requires_disability: false,
    citizenship: "Indian",
    min_work_experience: 0,
    required_gender: "Any",
    deadline: "2027-08-31",
    application_url: "https://kvpy.iisc.ac.in/",
    required_documents: ["Class 10 & 12 Marksheets", "KVPY Aptitude Test Score", "Aadhaar", "Bank Details"],
    application_effort_hours: 10,
    selection_criteria: "KVPY Aptitude Test + Interview",
    provider_type: "government",
    awards_per_year: 1000,
    competitive_ratio: "1:50",
    verified: true,
    notes: "Prestigious fellowship. Must clear KVPY aptitude exam and interview.",
  },
  {
    name: "Maulana Azad National Fellowship (MANF)",
    provider: "Ministry of Minority Affairs, India",
    amount_value: 420000,
    amount_currency: "INR",
    amount_string: "₹31,000–35,000/month",
    cover_type: "full",
    cover_details: "JRF + SRF fellowship for PhD scholars from minority communities",
    education_level: "doctorate",
    field_of_study: ["All"],
    country: "India",
    study_location: "India",
    max_income_annual: null,
    min_gpa: 55,
    requires_disability: false,
    citizenship: "Indian",
    min_work_experience: 0,
    required_gender: "Any",
    deadline: "2027-09-30",
    application_url: "https://manf.ugc.ac.in/",
    required_documents: ["NET/JRF Scorecard", "Minority Community Certificate", "Aadhaar", "Admission Letter (PhD)", "Degree Certificates"],
    application_effort_hours: 10,
    provider_type: "government",
    awards_per_year: 756,
    verified: true,
    notes: "For Muslim, Christian, Sikh, Buddhist, Parsi, Jain minority community students pursuing PhD.",
  },
  {
    name: "Narotam Sekhsaria Scholarship",
    provider: "Narotam Sekhsaria Foundation",
    amount_value: 3000000,
    amount_currency: "INR",
    amount_string: "Up to ₹30 lakh (loan-based)",
    cover_type: "partial",
    cover_details: "Interest-free loan for postgraduate studies abroad at top universities",
    education_level: "postgrad",
    field_of_study: ["All"],
    country: "USA",
    study_location: "Abroad",
    max_income_annual: null,
    min_gpa: 70,
    requires_disability: false,
    citizenship: "Indian",
    min_work_experience: 0,
    required_gender: "Any",
    deadline: "2027-04-30",
    application_url: "https://www.nsf.org.in/scholarships",
    required_documents: ["Statement of Purpose", "CV", "2 Reference Letters", "Transcripts", "Proof of Admission (Top 50 world university)", "Essays"],
    application_effort_hours: 20,
    selection_criteria: "Academic merit + Interview",
    provider_type: "ngo",
    competitive_ratio: "1:100",
    awards_per_year: 40,
    verified: true,
    notes: "Interest-free loan repayable after employment. Highly competitive for top global universities.",
  },
  {
    name: "Sitaram Jindal Scholarship",
    provider: "Sitaram Jindal Foundation",
    amount_value: 24000,
    amount_currency: "INR",
    amount_string: "₹1,000–2,000/month",
    cover_type: "partial",
    cover_details: "Monthly stipend based on course and family income",
    education_level: "undergrad",
    field_of_study: ["All"],
    country: "India",
    study_location: "India",
    max_income_annual: 250000,
    min_gpa: 55,
    requires_disability: false,
    citizenship: "Indian",
    min_work_experience: 0,
    required_gender: "Any",
    deadline: "2027-07-31",
    application_url: "https://www.sitaramjindalfoundation.org/",
    required_documents: ["10th Marksheet", "Current Year Marksheet", "Income Certificate", "Aadhaar", "Admission Proof"],
    application_effort_hours: 3,
    selection_criteria: "Need-based",
    provider_type: "ngo",
    competitive_ratio: "1:5",
    awards_per_year: 10000,
    verified: true,
    notes: "One of the most accessible scholarships. Low income threshold but high award count.",
  },
  {
    name: "JN TATA Endowment Loan Scholarship",
    provider: "JN Tata Endowment",
    amount_value: 1000000,
    amount_currency: "INR",
    amount_string: "Up to ₹10 lakh (loan) + gift scholarship component",
    cover_type: "partial",
    cover_details: "Loan scholarship for postgraduate studies abroad; top performers get grant",
    education_level: "postgrad",
    field_of_study: ["All"],
    country: "USA",
    study_location: "Abroad",
    max_income_annual: null,
    min_gpa: 70,
    requires_disability: false,
    citizenship: "Indian",
    min_work_experience: 0,
    required_gender: "Any",
    deadline: "2027-03-15",
    application_url: "https://jntataendowment.org/",
    required_documents: ["Statement of Purpose", "Proof of Admission", "Academic Transcripts", "CV", "2 References", "Bank Statement"],
    application_effort_hours: 15,
    selection_criteria: "Merit + Interview",
    provider_type: "ngo",
    competitive_ratio: "1:40",
    awards_per_year: 150,
    verified: true,
    notes: "Loan converts to gift for scholars who return to India and contribute to development.",
  },
  {
    name: "Canada-ASEAN Scholarships (CAES)",
    provider: "Global Affairs Canada",
    amount_value: 3300000,
    amount_currency: "INR",
    amount_string: "CAD 50,000 full funding",
    cover_type: "full",
    cover_details: "Tuition, living, health insurance, return airfare, visa fees",
    education_level: "postgrad",
    field_of_study: ["All"],
    country: "Canada",
    study_location: "Abroad",
    max_income_annual: null,
    min_gpa: 65,
    requires_disability: false,
    citizenship: "Any",
    min_work_experience: 0,
    required_gender: "Any",
    deadline: "2027-02-28",
    application_url: "https://www.educanada.ca/scholarships-bourses/can/institutions/caes-pfac.aspx",
    required_documents: ["Motivation Letter", "CV", "Transcripts", "Language Proof (IELTS 6.5+)", "2 References", "Research Proposal"],
    application_effort_hours: 20,
    provider_type: "international",
    competitive_ratio: "1:80",
    awards_per_year: 100,
    verified: true,
    notes: "One-year Master's or short courses at Canadian universities. Includes ASEAN nations but open to Indians too.",
  },
  {
    name: "Rhodes Scholarship (India)",
    provider: "Rhodes Trust, Oxford",
    amount_value: 7500000,
    amount_currency: "INR",
    amount_string: "Full funding at Oxford (~£60,000/year)",
    cover_type: "full",
    cover_details: "Tuition fees, stipend, airfare, health insurance at Oxford",
    education_level: "postgrad",
    field_of_study: ["All"],
    country: "UK",
    study_location: "Abroad",
    max_income_annual: null,
    min_gpa: 85,
    requires_disability: false,
    citizenship: "Indian",
    min_work_experience: 0,
    required_gender: "Any",
    deadline: "2027-07-31",
    application_url: "https://www.rhodeshouse.ox.ac.uk/scholarships/the-rhodes-scholarship/",
    required_documents: ["Personal Statement", "4 Academic/Professional References", "Transcripts", "IELTS/TOEFL", "Leadership Evidence Portfolio", "Passport"],
    application_effort_hours: 60,
    selection_criteria: "Academic excellence + Leadership + Character",
    provider_type: "international",
    competitive_ratio: "1:1000",
    awards_per_year: 6,
    verified: true,
    notes: "Most prestigious scholarship in the world. Only 6 awarded from India per year. Must demonstrate outstanding academic AND leadership achievement.",
  },
  {
    name: "Chevening Scholarship (UK)",
    provider: "UK Government (FCDO)",
    amount_value: 5800000,
    amount_currency: "INR",
    amount_string: "Full funding (~£45,000)",
    cover_type: "full",
    cover_details: "Tuition, monthly living allowance, economy travel, visa fees",
    education_level: "postgrad",
    field_of_study: ["All"],
    country: "UK",
    study_location: "Abroad",
    max_income_annual: null,
    min_gpa: 65,
    requires_disability: false,
    citizenship: "Indian",
    min_work_experience: 2,
    required_gender: "Any",
    deadline: "2027-11-05",
    application_url: "https://www.chevening.org/apply/",
    required_documents: ["Personal Statement (4 essays)", "2 Professional References", "Transcripts", "IELTS (6.5+)", "CV", "Passport"],
    application_effort_hours: 30,
    selection_criteria: "Leadership + Academic merit + Impact potential",
    provider_type: "international",
    competitive_ratio: "1:200",
    awards_per_year: 70,
    verified: true,
    notes: "For future leaders. Requires 2 years work experience. Apply Nov–Nov cycle.",
  },
  // ── GOVERNMENT SCHEMES (INDIA) ──────────────────────────────────────────────
  {
    name: "AICTE Pragati Scholarship Scheme for Female Students",
    provider: "All India Council for Technical Education (AICTE)",
    amount_value: 50000,
    amount_currency: "INR",
    amount_string: "₹50,000/year",
    cover_type: "partial",
    cover_details: "Lump sum amount towards college fees, books, equipment, and hostel fees",
    education_level: "undergrad",
    field_of_study: ["Engineering", "Technology", "Pharmacy", "Architecture"],
    country: "India",
    study_location: "India",
    max_income_annual: 800000,
    min_gpa: 50,
    requires_disability: false,
    citizenship: "Indian",
    min_work_experience: 0,
    required_gender: "Female",
    deadline: "2027-10-31",
    application_url: "https://scholarships.gov.in",
    required_documents: ["10th & 12th Marksheet", "Income Certificate", "Aadhaar Card", "Admission Proof from AICTE institute"],
    application_effort_hours: 4,
    selection_criteria: "Merit in qualifying examination",
    provider_type: "government",
    awards_per_year: 10000,
    verified: true,
    notes: "Up to 2 girls per family enrolled in AICTE-approved degree or diploma courses.",
  },
  {
    name: "AICTE Saksham Scholarship for Differently Abled Students",
    provider: "All India Council for Technical Education (AICTE)",
    amount_value: 50000,
    amount_currency: "INR",
    amount_string: "₹50,000/year",
    cover_type: "partial",
    cover_details: "Financial assistance towards college fees, books, computer, and assistive devices",
    education_level: "undergrad",
    field_of_study: ["Engineering", "Technology", "Pharmacy"],
    country: "India",
    study_location: "India",
    max_income_annual: 800000,
    min_gpa: 45,
    requires_disability: true,
    citizenship: "Indian",
    min_work_experience: 0,
    required_gender: "Any",
    deadline: "2027-10-31",
    application_url: "https://scholarships.gov.in",
    required_documents: ["Disability Certificate (40%+)", "10th/12th Marksheet", "Income Certificate", "Aadhaar Card"],
    application_effort_hours: 4,
    selection_criteria: "Merit in qualifying exam + Disability verification",
    provider_type: "government",
    awards_per_year: 1000,
    verified: true,
    notes: "Specially designed for students with at least 40% disability pursuing technical education.",
  },
  {
    name: "PMSSS — Prime Minister's Special Scholarship Scheme (J&K & Ladakh)",
    provider: "AICTE / Ministry of Education, India",
    amount_value: 300000,
    amount_currency: "INR",
    amount_string: "Up to ₹3.0 lakh/year (Tuition + Hostel)",
    cover_type: "full",
    cover_details: "Full academic fee paid directly to college + ₹1.0 lakh annual maintenance fee",
    education_level: "undergrad",
    field_of_study: ["General Degree", "Engineering", "Medicine", "Nursing", "All"],
    country: "India",
    study_location: "India",
    max_income_annual: 800000,
    min_gpa: 55,
    requires_disability: false,
    citizenship: "Indian",
    min_work_experience: 0,
    required_gender: "Any",
    deadline: "2027-08-15",
    application_url: "https://www.aicte-jk-scholarship-gov.in",
    required_documents: ["J&K/Ladakh Domicile Certificate", "12th Marksheet", "Income Certificate", "Aadhaar Card"],
    application_effort_hours: 6,
    selection_criteria: "Merit in Class 12 counselling",
    provider_type: "government",
    awards_per_year: 5000,
    verified: true,
    notes: "Exclusively for domicile students of Jammu & Kashmir and Ladakh studying outside J&K.",
  },
  {
    name: "Ishan Uday Special Scholarship for North Eastern Region (NER)",
    provider: "University Grants Commission (UGC)",
    amount_value: 93600,
    amount_currency: "INR",
    amount_string: "₹7,800/month (₹93,600/year)",
    cover_type: "partial",
    cover_details: "Monthly stipend for general, professional, and medical degree students",
    education_level: "undergrad",
    field_of_study: ["All"],
    country: "India",
    study_location: "India",
    max_income_annual: 450000,
    min_gpa: 50,
    requires_disability: false,
    citizenship: "Indian",
    min_work_experience: 0,
    required_gender: "Any",
    deadline: "2027-11-30",
    application_url: "https://scholarships.gov.in",
    required_documents: ["Domicile Certificate of NER State", "12th Marksheet", "Income Certificate", "College Admission Proof"],
    application_effort_hours: 4,
    selection_criteria: "Merit in Class 12 + Income quota",
    provider_type: "government",
    awards_per_year: 10000,
    verified: true,
    notes: "Reserved for domicile students of 8 North Eastern states (Assam, Meghalaya, Manipur, Mizoram, Nagaland, Tripura, Arunachal Pradesh, Sikkim).",
  },
  {
    name: "National Overseas Scholarship (NOS) for SC Candidates",
    provider: "Ministry of Social Justice and Empowerment, Govt of India",
    amount_value: 3500000,
    amount_currency: "INR",
    amount_string: "Full Tuition + ~$15,400 Annual Allowance",
    cover_type: "full",
    cover_details: "Complete tuition fees, annual maintenance allowance, airfare, visa fees, and contingency allowance",
    education_level: "postgrad",
    field_of_study: ["Engineering", "Management", "Pure Sciences", "Medicine", "Social Sciences", "Humanities"],
    country: "USA",
    study_location: "Abroad",
    max_income_annual: 800000,
    min_gpa: 60,
    requires_disability: false,
    citizenship: "Indian",
    min_work_experience: 0,
    required_gender: "Any",
    deadline: "2027-03-31",
    application_url: "https://nosmsje.gov.in",
    required_documents: ["Caste Certificate (SC)", "Income Certificate", "Unconditional Offer Letter from Top 500 QS University", "Passport", "10th/12th/UG Degree Marksheets"],
    application_effort_hours: 15,
    selection_criteria: "QS University Ranking + Merit + Income",
    provider_type: "government",
    awards_per_year: 125,
    verified: true,
    notes: "Provides full funding for Master's and PhD at foreign universities ranking in Top 500 QS World Rankings.",
  },
  {
    name: "Central Sector Scheme of Top Class Education for SC Students",
    provider: "Ministry of Social Justice and Empowerment, India",
    amount_value: 200000,
    amount_currency: "INR",
    amount_string: "Full Tuition Fee (up to ₹2.0 lakh) + ₹86,000 Living Allowance",
    cover_type: "full",
    cover_details: "Full tuition reimbursement + living allowance + ₹45,000 for computer + ₹5,000 books",
    education_level: "undergrad",
    field_of_study: ["Engineering", "Medicine", "Law", "Management"],
    country: "India",
    study_location: "India",
    max_income_annual: 800000,
    min_gpa: 50,
    requires_disability: false,
    citizenship: "Indian",
    min_work_experience: 0,
    required_gender: "Any",
    deadline: "2027-11-15",
    application_url: "https://scholarships.gov.in",
    required_documents: ["SC Caste Certificate", "Income Certificate", "Admission Letter into notified premier institute (IIT/IIM/NIT/NLUs)", "Aadhaar Card"],
    application_effort_hours: 5,
    selection_criteria: "Admission into premier top-class notified institutes",
    provider_type: "government",
    awards_per_year: 4200,
    verified: true,
    notes: "Covers full tuition and living costs for SC students getting admission into IITs, NITs, IIMs, NLUs, and premier central institutes.",
  },
  {
    name: "Begum Hazrat Mahal National Scholarship for Minority Girls",
    provider: "Maulana Azad Education Foundation (MAEF)",
    amount_value: 12000,
    amount_currency: "INR",
    amount_string: "₹6,000 to ₹12,000/year",
    cover_type: "partial",
    cover_details: "Direct financial assistance for school fees and study materials",
    education_level: "school",
    field_of_study: ["All"],
    country: "India",
    study_location: "India",
    max_income_annual: 200000,
    min_gpa: 50,
    requires_disability: false,
    citizenship: "Indian",
    min_work_experience: 0,
    required_gender: "Female",
    deadline: "2027-11-30",
    application_url: "https://scholarships.gov.in",
    required_documents: ["Minority Self-Declaration", "Income Certificate", "School Marksheet", "Aadhaar Card", "Bank Passbook"],
    application_effort_hours: 3,
    selection_criteria: "Merit in previous class + Income priority",
    provider_type: "government",
    awards_per_year: 100000,
    verified: true,
    notes: "For girl students belonging to 6 notified minority communities (Muslim, Christian, Sikh, Buddhist, Jain, Parsi) studying in Classes 9 to 12.",
  },
  {
    name: "CSIR-UGC Junior Research Fellowship (JRF) in Science & Technology",
    provider: "Council of Scientific and Industrial Research (CSIR)",
    amount_value: 444000,
    amount_currency: "INR",
    amount_string: "₹37,000/month + HRA (₹4.44 lakh/year)",
    cover_type: "full",
    cover_details: "Monthly stipend of ₹37,000 for first 2 years, upgradable to SRF ₹42,000/month + Contingency ₹20,000/year",
    education_level: "doctorate",
    field_of_study: ["Chemical Sciences", "Earth Sciences", "Life Sciences", "Mathematical Sciences", "Physical Sciences", "Engineering"],
    country: "India",
    study_location: "India",
    max_income_annual: null,
    min_gpa: 55,
    requires_disability: false,
    citizenship: "Indian",
    min_work_experience: 0,
    required_gender: "Any",
    deadline: "2027-05-30",
    application_url: "https://csirnet.nta.ac.in",
    required_documents: ["Master's Degree Certificate (M.Sc/M.Tech/BS-MS)", "Category Certificate", "CSIR-UGC NET Scorecard"],
    application_effort_hours: 20,
    selection_criteria: "Rank in CSIR-UGC NET National Entrance Examination",
    provider_type: "government",
    awards_per_year: 2500,
    verified: true,
    notes: "Premier research fellowship in India for pursuing PhD in basic and applied sciences.",
  },
  {
    name: "DST WISE-KIRAN Fellowship for Women Scientists",
    provider: "Department of Science and Technology (DST), Govt of India",
    amount_value: 660000,
    amount_currency: "INR",
    amount_string: "₹55,000/month + HRA + Research Grant",
    cover_type: "full",
    cover_details: "Monthly fellowship for women scientists with a break in career to resume research in S&T",
    education_level: "doctorate",
    field_of_study: ["Physical Sciences", "Chemical Sciences", "Life Sciences", "Engineering", "Mathematical Sciences"],
    country: "India",
    study_location: "India",
    max_income_annual: null,
    min_gpa: 60,
    requires_disability: false,
    citizenship: "Indian",
    min_work_experience: 0,
    required_gender: "Female",
    deadline: "2027-12-31",
    application_url: "https://dst.gov.in/scientific-programmes/st-and-women/kiran-scheme",
    required_documents: ["PhD/M.Tech Degree", "Break in Career Proof", "Detailed Research Proposal", "Host Institute Acceptance Letter"],
    application_effort_hours: 25,
    selection_criteria: "Quality of research proposal + Expert panel interview",
    provider_type: "government",
    awards_per_year: 500,
    verified: true,
    notes: "Specially designed for women scientists between 27 and 57 years of age who had a career break.",
  },
  {
    name: "UGC Savitribai Phule Single Girl Child Fellowship for Social Sciences",
    provider: "University Grants Commission (UGC)",
    amount_value: 372000,
    amount_currency: "INR",
    amount_string: "₹31,000/month (₹3.72 lakh/year)",
    cover_type: "full",
    cover_details: "Monthly fellowship + contingency grant for pursuing PhD in Humanities and Social Sciences",
    education_level: "doctorate",
    field_of_study: ["Humanities", "Social Sciences", "Economics", "Sociology", "Psychology"],
    country: "India",
    study_location: "India",
    max_income_annual: null,
    min_gpa: 55,
    requires_disability: false,
    citizenship: "Indian",
    min_work_experience: 0,
    required_gender: "Female",
    deadline: "2027-10-15",
    application_url: "https://scholarships.gov.in",
    required_documents: ["Single Girl Child Affidavit on Stamp Paper", "Postgraduation Marksheet", "PhD Registration Letter"],
    application_effort_hours: 6,
    selection_criteria: "Academic record + Single girl child verification",
    provider_type: "government",
    awards_per_year: 1000,
    verified: true,
    notes: "For female candidates who are the single girl child of their parents registered in regular PhD programs.",
  },

  // ── CORPORATE & NGO SCHOLARSHIPS (INDIA) ─────────────────────────────────────
  {
    name: "Kotak Kanya Scholarship for Female Undergraduates",
    provider: "Kotak Education Foundation",
    amount_value: 150000,
    amount_currency: "INR",
    amount_string: "Up to ₹1.5 lakh/year",
    cover_type: "partial",
    cover_details: "Tuition fees, hostel fees, books, laptop, and academic expenses",
    education_level: "undergrad",
    field_of_study: ["Engineering", "Medicine", "Architecture", "Design", "LL.B."],
    country: "India",
    study_location: "India",
    max_income_annual: 650000,
    min_gpa: 75,
    requires_disability: false,
    citizenship: "Indian",
    min_work_experience: 0,
    required_gender: "Female",
    deadline: "2027-09-30",
    application_url: "https://kotakeducation.org/kotak-kanya-scholarship/",
    required_documents: ["Class 12 Marksheet (75%+ required)", "Income Certificate", "Admission Proof in NIRF top institution", "Aadhaar Card"],
    application_effort_hours: 5,
    selection_criteria: "Class 12 Merit (75%+) + Income verification + Telephonic Interview",
    provider_type: "corporate",
    awards_per_year: 300,
    verified: true,
    notes: "Empowers meritorious girl students from low-income families to pursue professional courses at premier institutes.",
  },
  {
    name: "Keep India Smiling Foundational Scholarship (Colgate-Palmolive)",
    provider: "Colgate-Palmolive (India) Limited",
    amount_value: 50000,
    amount_currency: "INR",
    amount_string: "₹30,000 to ₹50,000/year",
    cover_type: "partial",
    cover_details: "Financial support for foundational education, graduation, or sports mentorship",
    education_level: "undergrad",
    field_of_study: ["Engineering", "Medicine", "B.Sc", "B.Com", "B.A.", "All"],
    country: "India",
    study_location: "India",
    max_income_annual: 500000,
    min_gpa: 60,
    requires_disability: false,
    citizenship: "Indian",
    min_work_experience: 0,
    required_gender: "Any",
    deadline: "2027-12-31",
    application_url: "https://www.colgatekeepindiasmiling.com",
    required_documents: ["Class 10 & 12 Marksheets", "Income Certificate", "Government ID", "Admission Fee Receipt"],
    application_effort_hours: 4,
    selection_criteria: "Merit in Class 10/12 + Need evaluation",
    provider_type: "corporate",
    awards_per_year: 500,
    verified: true,
    notes: "Provides financial aid and mentorship for students pursuing 3-year or 4-year degree programs.",
  },
  {
    name: "Santoor Women's Scholarship (Wipro Cares)",
    provider: "Wipro Cares & Azim Premji Foundation",
    amount_value: 24000,
    amount_currency: "INR",
    amount_string: "₹24,000/year",
    cover_type: "partial",
    cover_details: "Annual support for tuition fees and education expenses",
    education_level: "undergrad",
    field_of_study: ["Humanities", "Arts", "Sciences", "Commerce"],
    country: "India",
    study_location: "India",
    max_income_annual: null,
    min_gpa: 55,
    requires_disability: false,
    citizenship: "Indian",
    min_work_experience: 0,
    required_gender: "Female",
    deadline: "2027-09-15",
    application_url: "https://www.santoorscholarships.com",
    required_documents: ["Class 10 & 12 Marksheet from Govt School", "Aadhaar Card", "Bank Passbook", "College Admission ID"],
    application_effort_hours: 3,
    selection_criteria: "Schooling from Govt school in AP/Telangana/Karnataka/Chhattisgarh + Merit",
    provider_type: "corporate",
    awards_per_year: 900,
    verified: true,
    notes: "For young women from underprivileged backgrounds who passed Class 12 from a government school.",
  },
  {
    name: "L'Oréal India For Women in Science Scholarship",
    provider: "L'Oréal India",
    amount_value: 250000,
    amount_currency: "INR",
    amount_string: "₹2.5 lakh (total over degree course)",
    cover_type: "partial",
    cover_details: "Covers tuition fees for undergraduate studies in science, engineering, or medical fields",
    education_level: "undergrad",
    field_of_study: ["Pure Sciences", "Applied Sciences", "Engineering", "Medicine", "Biotechnology"],
    country: "India",
    study_location: "India",
    max_income_annual: 600000,
    min_gpa: 85,
    requires_disability: false,
    citizenship: "Indian",
    min_work_experience: 0,
    required_gender: "Female",
    deadline: "2027-01-31",
    application_url: "https://www.loreal.com/en/india/articles/commitments-society/for-women-in-science-scholarship/",
    required_documents: ["Class 12 Marksheet (85%+ in PCM/PCB)", "Income Certificate", "Essay / Statement of Purpose", "Proof of Admission"],
    application_effort_hours: 6,
    selection_criteria: "Class 12 score (85%+) + Statement of Purpose + Telephonic Interview",
    provider_type: "corporate",
    awards_per_year: 50,
    verified: true,
    notes: "Encourages young women to pursue higher education in scientific disciplines. Requires 85%+ in PCB/PCM in Class 12.",
  },
  {
    name: "SBIF Asha Scholarship Program (SBI Foundation)",
    provider: "SBI Foundation",
    amount_value: 75000,
    amount_currency: "INR",
    amount_string: "₹15,000 to ₹75,000/year",
    cover_type: "partial",
    cover_details: "Financial aid for students in school (Class 6-12), Undergrad, Postgrad, and IIT/IIM students",
    education_level: "undergrad",
    field_of_study: ["All"],
    country: "India",
    study_location: "India",
    max_income_annual: 300000,
    min_gpa: 75,
    requires_disability: false,
    citizenship: "Indian",
    min_work_experience: 0,
    required_gender: "Any",
    deadline: "2027-11-30",
    application_url: "https://www.sbifoundation.in",
    required_documents: ["Marksheet of previous academic year (75%+)", "Income Certificate", "Aadhaar Card", "Admission Receipt"],
    application_effort_hours: 4,
    selection_criteria: "Academic score (75%+) + Low family income priority",
    provider_type: "corporate",
    awards_per_year: 3000,
    verified: true,
    notes: "One of India's largest corporate CSR scholarship initiatives supporting meritorious low-income students.",
  },
  {
    name: "ONGC Foundation Merit Scholarship for SC/ST/OBC Students",
    provider: "ONGC Foundation",
    amount_value: 48000,
    amount_currency: "INR",
    amount_string: "₹4,000/month (₹48,000/year)",
    cover_type: "partial",
    cover_details: "Financial assistance towards professional degree courses in Engineering, Geology, Geophysics, and MBA",
    education_level: "undergrad",
    field_of_study: ["Engineering", "Geology", "Geophysics", "MBA", "MBBS"],
    country: "India",
    study_location: "India",
    max_income_annual: 200000,
    min_gpa: 60,
    requires_disability: false,
    citizenship: "Indian",
    min_work_experience: 0,
    required_gender: "Any",
    deadline: "2027-10-15",
    application_url: "https://www.ongcscholar.org",
    required_documents: ["Category Certificate (SC/ST/OBC)", "Class 12 / Graduation Marksheets", "Income Certificate", "ECS Mandate Form"],
    application_effort_hours: 5,
    selection_criteria: "Merit in qualifying examination + Caste quota",
    provider_type: "corporate",
    awards_per_year: 2000,
    verified: true,
    notes: "50% of total scholarships are reserved for girl candidates.",
  },
  {
    name: "Coal India Limited (CIL) Merit Scholarship for Engineering & Medical",
    provider: "Coal India Limited",
    amount_value: 100000,
    amount_currency: "INR",
    amount_string: "Full Tuition + Hostel Fees Reimbursement",
    cover_type: "full",
    cover_details: "Reimbursement of tuition fee, hostel charges, and book allowance",
    education_level: "undergrad",
    field_of_study: ["Engineering", "Medicine"],
    country: "India",
    study_location: "India",
    max_income_annual: 500000,
    min_gpa: 65,
    requires_disability: false,
    citizenship: "Indian",
    min_work_experience: 0,
    required_gender: "Any",
    deadline: "2027-09-30",
    application_url: "https://www.coalindia.in",
    required_documents: ["BPL / Income Certificate", "JEE Main/NEET Rank Card", "College Fee Receipts", "Aadhaar Card"],
    application_effort_hours: 4,
    selection_criteria: "JEE Main / NEET All India Rank",
    provider_type: "corporate",
    awards_per_year: 100,
    verified: true,
    notes: "Targeted at BPL families and land-ousted families near CIL mining operational zones.",
  },
  {
    name: "Infosys Foundation STEM Fellowship for Women Researchers",
    provider: "Infosys Foundation",
    amount_value: 500000,
    amount_currency: "INR",
    amount_string: "₹5.0 lakh/year",
    cover_type: "full",
    cover_details: "Fellowship grant for women pursuing doctoral or post-doctoral STEM research in India",
    education_level: "doctorate",
    field_of_study: ["Computer Science", "Artificial Intelligence", "Data Science", "Mathematics", "Physics"],
    country: "India",
    study_location: "India",
    max_income_annual: null,
    min_gpa: 70,
    requires_disability: false,
    citizenship: "Indian",
    min_work_experience: 0,
    required_gender: "Female",
    deadline: "2027-08-31",
    application_url: "https://www.infosys.com/infosys-foundation.html",
    required_documents: ["M.Tech/M.Sc Degree", "Research Proposal", "Publication List", "Recommendation Letters"],
    application_effort_hours: 15,
    selection_criteria: "Peer review of research proposal + Tech panel interview",
    provider_type: "corporate",
    awards_per_year: 25,
    verified: true,
    notes: "Aims to increase female representation in advanced AI, Computer Science, and Deep Tech research.",
  },
  {
    name: "Generation Google Scholarship (APAC Region)",
    provider: "Google",
    amount_value: 210000,
    amount_currency: "INR",
    amount_string: "$2,500 USD (~₹2.1 lakh)",
    cover_type: "partial",
    cover_details: "Financial award for tuition fees, books, supplies, and technical equipment",
    education_level: "undergrad",
    field_of_study: ["Computer Science", "Computer Engineering", "Software Engineering", "Related Tech Fields"],
    country: "India",
    study_location: "India",
    max_income_annual: null,
    min_gpa: 70,
    requires_disability: false,
    citizenship: "Indian",
    min_work_experience: 0,
    required_gender: "Female",
    deadline: "2027-04-30",
    application_url: "https://buildyourfuture.withgoogle.com/scholarships/generation-google-scholarship-apac",
    required_documents: ["Resume/CV", "Academic Transcripts", "2 Technical Essays", "Google Online Challenge Score"],
    application_effort_hours: 20,
    selection_criteria: "Commitment to diversity, demonstrated leadership, and academic performance",
    provider_type: "corporate",
    awards_per_year: 60,
    verified: true,
    notes: "Designed for female students studying Computer Science or closely related technical degrees.",
  },
  {
    name: "Adobe India Women in Technology Scholarship",
    provider: "Adobe Research India",
    amount_value: 600000,
    amount_currency: "INR",
    amount_string: "Full Tuition + Internship at Adobe + Grace Hopper Conference Travel",
    cover_type: "full",
    cover_details: "Tuition fee coverage + paid summer internship at Adobe India + conference mentorship",
    education_level: "undergrad",
    field_of_study: ["Computer Science", "Data Science", "Artificial Intelligence", "Information Technology"],
    country: "India",
    study_location: "India",
    max_income_annual: null,
    min_gpa: 75,
    requires_disability: false,
    citizenship: "Indian",
    min_work_experience: 0,
    required_gender: "Female",
    deadline: "2027-09-30",
    application_url: "https://research.adobe.com/scholarship/",
    required_documents: ["Resume", "Academic Transcripts", "Statement of Purpose", "1 Recommendation Letter", "Optional Short Video"],
    application_effort_hours: 12,
    selection_criteria: "Technical innovation + Academic achievement + Passion for technology",
    provider_type: "corporate",
    awards_per_year: 10,
    verified: true,
    notes: "Includes a guaranteed summer internship at Adobe India R&D centers.",
  },
  {
    name: "IDFC FIRST Bank MBA Scholarship",
    provider: "IDFC FIRST Bank",
    amount_value: 200000,
    amount_currency: "INR",
    amount_string: "₹2.0 lakh (₹1.0 lakh/year for 2 years)",
    cover_type: "partial",
    cover_details: "Tuition fee reimbursement for students pursuing full-time 2-year MBA programs",
    education_level: "postgrad",
    field_of_study: ["MBA", "PGDM", "Management"],
    country: "India",
    study_location: "India",
    max_income_annual: 600000,
    min_gpa: 60,
    requires_disability: false,
    citizenship: "Indian",
    min_work_experience: 0,
    required_gender: "Any",
    deadline: "2027-07-31",
    application_url: "https://www.idfcfirstbank.com/csr-activities/educational-scholarships",
    required_documents: ["CAT/XAT Scorecard", "Graduation Marksheet", "Income Certificate", "Admission Offer Letter from Partner B-School"],
    application_effort_hours: 5,
    selection_criteria: "Admission to top 150 B-schools + Family income evaluation",
    provider_type: "corporate",
    awards_per_year: 350,
    verified: true,
    notes: "Covers students admitted into 150+ selected B-Schools across India including IIMs, XLRI, NMIMS, MDI.",
  },
  {
    name: "Sitaram Jindal Foundation Merit Scholarship",
    provider: "Sitaram Jindal Foundation",
    amount_value: 30000,
    amount_currency: "INR",
    amount_string: "₹500 to ₹2,500/month",
    cover_type: "partial",
    cover_details: "Monthly financial scholarship for school, ITI, Diploma, Undergrad, and Postgrad students",
    education_level: "undergrad",
    field_of_study: ["All"],
    country: "India",
    study_location: "India",
    max_income_annual: 400000,
    min_gpa: 65,
    requires_disability: false,
    citizenship: "Indian",
    min_work_experience: 0,
    required_gender: "Any",
    deadline: "2027-12-31",
    application_url: "https://www.sitaramjindalfoundation.org",
    required_documents: ["Marksheets of last exam", "Income Certificate", "Principal Recommendation Annexure", "Aadhaar Card"],
    application_effort_hours: 4,
    selection_criteria: "Academic cutoff marks (65%+ for boys, 60%+ for girls)",
    provider_type: "ngo",
    awards_per_year: 12000,
    verified: true,
    notes: "Applications accepted offline/online year-round. Lower cutoff marks for female students.",
  },
  {
    name: "Vidyasaarathi Corporate CSR Scholarships (NSDL)",
    provider: "NSDL e-Governance / Corporate Sponsors",
    amount_value: 50000,
    amount_currency: "INR",
    amount_string: "₹10,000 to ₹50,000/year",
    cover_type: "partial",
    cover_details: "Direct financial support for ITI, Diploma, UG, and PG students sponsored by top corporate CSRs",
    education_level: "undergrad",
    field_of_study: ["Engineering", "B.Sc", "B.Com", "B.A.", "Diploma", "All"],
    country: "India",
    study_location: "India",
    max_income_annual: 500000,
    min_gpa: 50,
    requires_disability: false,
    citizenship: "Indian",
    min_work_experience: 0,
    required_gender: "Any",
    deadline: "2027-10-31",
    application_url: "https://www.vidyasaarathi.co.in",
    required_documents: ["10th/12th Marksheet", "Income Certificate", "College Fee Structure", "Bank Passbook"],
    application_effort_hours: 3,
    selection_criteria: "Merit-cum-means selection by corporate CSR committee",
    provider_type: "corporate",
    awards_per_year: 5000,
    verified: true,
    notes: "Single portal hosting multiple corporate scholarships from ACC, ACCENTURE, TATA POWER, JSW, NSDL, etc.",
  },
  {
    name: "LIC Golden Jubilee Scholarship Scheme",
    provider: "Life Insurance Corporation of India (LIC)",
    amount_value: 20000,
    amount_currency: "INR",
    amount_string: "₹20,000/year (Professional) / ₹10,000/year (General)",
    cover_type: "partial",
    cover_details: "Annual stipend disbursed in installments for higher studies in medicine, engineering, graduation",
    education_level: "undergrad",
    field_of_study: ["Engineering", "Medicine", "Diploma", "Arts", "Science", "Commerce"],
    country: "India",
    study_location: "India",
    max_income_annual: 250000,
    min_gpa: 60,
    requires_disability: false,
    citizenship: "Indian",
    min_work_experience: 0,
    required_gender: "Any",
    deadline: "2027-12-15",
    application_url: "https://licindia.in/Golden-Jubilee-Scholarship",
    required_documents: ["Class 10/12 Marksheet (60%+)", "Income Certificate", "Bank Account Details", "College Fee Receipt"],
    application_effort_hours: 4,
    selection_criteria: "Percentage in Class 10/12 + Family income preference",
    provider_type: "corporate",
    awards_per_year: 2000,
    verified: true,
    notes: "Requires minimum 60% marks in Class 12 or equivalent.",
  },

  // ── INTERNATIONAL / STUDY ABROAD SCHOLARSHIPS ───────────────────────────────
  {
    name: "DAAD Helmut-Schmidt Programme (Master's in Germany)",
    provider: "German Academic Exchange Service (DAAD)",
    amount_value: 1800000,
    amount_currency: "INR",
    amount_string: "Full Tuition + €934/month stipend (~₹18 lakh/year)",
    cover_type: "full",
    cover_details: "Monthly stipend of €934, health insurance, travel allowance, and German language course",
    education_level: "postgrad",
    field_of_study: ["Public Policy", "Governance", "Development Studies", "Economics", "Political Science"],
    country: "Germany",
    study_location: "Abroad",
    max_income_annual: null,
    min_gpa: 70,
    requires_disability: false,
    citizenship: "Indian",
    min_work_experience: 1,
    required_gender: "Any",
    deadline: "2027-07-31",
    application_url: "https://www.daad.de/en/study-and-research-in-germany/scholarships/",
    required_documents: ["DAAD Application Form", "Motivation Letter", "CV (Europass)", "Bachelor Degree", "English Proficiency (IELTS/TOEFL)"],
    application_effort_hours: 25,
    selection_criteria: "Academic excellence + Political/Social commitment",
    provider_type: "international",
    awards_per_year: 80,
    verified: true,
    notes: "Prepares future leaders in politics, law, economics, and public administration at top German universities.",
  },
  {
    name: "Erasmus Mundus Joint Master Degrees (EMJMD Europe)",
    provider: "European Commission / European Union",
    amount_value: 3000000,
    amount_currency: "INR",
    amount_string: "Full Funding (~€24,000/year)",
    cover_type: "full",
    cover_details: "Full tuition coverage, monthly allowance of €1,400, travel costs, and installation grant",
    education_level: "postgrad",
    field_of_study: ["All"],
    country: "Europe",
    study_location: "Abroad",
    max_income_annual: null,
    min_gpa: 70,
    requires_disability: false,
    citizenship: "Any",
    min_work_experience: 0,
    required_gender: "Any",
    deadline: "2027-01-15",
    application_url: "https://ec.europa.eu/programmes/erasmus-plus/opportunities/individuals/students/erasmus-mundus-joint-master-degrees_en",
    required_documents: ["Bachelor Degree Transcripts", "2 Recommendation Letters", "Motivation Essay", "IELTS/TOEFL Scorecard", "Passport"],
    application_effort_hours: 40,
    selection_criteria: "International consortium peer review of academic portfolio",
    provider_type: "international",
    awards_per_year: 2500,
    verified: true,
    notes: "Allows students to study at 2 or 3 different European universities across multiple countries.",
  },
  {
    name: "Inlaks Shivdasani Foundation Abroad Scholarship",
    provider: "Inlaks Shivdasani Foundation",
    amount_value: 8300000,
    amount_currency: "INR",
    amount_string: "Up to $100,000 USD (~₹83 lakh)",
    cover_type: "full",
    cover_details: "Covers tuition fees, living expenses, health allowance, and one-way travel",
    education_level: "postgrad",
    field_of_study: ["Humanities", "Social Sciences", "Fine Arts", "Architecture", "Law", "Sciences"],
    country: "USA",
    study_location: "Abroad",
    max_income_annual: null,
    min_gpa: 70,
    requires_disability: false,
    citizenship: "Indian",
    min_work_experience: 0,
    required_gender: "Any",
    deadline: "2027-03-30",
    application_url: "https://www.inlaksfoundation.org/scholarships/",
    required_documents: ["Unconditional Admission Letter from Top US/UK/European University", "Portfolio / Writing Sample", "Transcripts", "CV"],
    application_effort_hours: 30,
    selection_criteria: "Exceptional talent + Interview with Inlaks Selection Board",
    provider_type: "ngo",
    awards_per_year: 15,
    verified: true,
    notes: "For outstanding young Indians studying at top universities in America, UK, and Europe. Candidates must be under 30 years old.",
  },
  {
    name: "Narotam Sekhsaria Foundation Postgraduate Scholarship",
    provider: "Narotam Sekhsaria Foundation",
    amount_value: 2000000,
    amount_currency: "INR",
    amount_string: "Up to ₹20.0 lakh interest-free loan scholarship",
    cover_type: "partial",
    cover_details: "Interest-free loan scholarship for master's and doctoral studies in India and abroad",
    education_level: "postgrad",
    field_of_study: ["Pure Sciences", "Applied Sciences", "Engineering", "Medicine", "Humanities", "Management"],
    country: "India",
    study_location: "Both",
    max_income_annual: null,
    min_gpa: 65,
    requires_disability: false,
    citizenship: "Indian",
    min_work_experience: 0,
    required_gender: "Any",
    deadline: "2027-03-15",
    application_url: "https://pg.nsfoundation.co.in",
    required_documents: ["Graduation Marksheets", "Admission Proof from top global university", "Statement of Purpose", "2 References"],
    application_effort_hours: 15,
    selection_criteria: "Academic record + Orientation test + Personal Interview",
    provider_type: "ngo",
    awards_per_year: 40,
    verified: true,
    notes: "Includes a unique mentorship program with industry stalwarts alongside financial support.",
  },
  {
    name: "Commonwealth Master's & PhD Scholarships (UK)",
    provider: "Commonwealth Scholarship Commission (CSC UK)",
    amount_value: 5500000,
    amount_currency: "INR",
    amount_string: "Full Funding (~£42,000/year)",
    cover_type: "full",
    cover_details: "Approved tuition fees, monthly stipend (£1,347/month), airfare, and warm clothing allowance",
    education_level: "postgrad",
    field_of_study: ["Science & Tech", "Health", "Development", "Global Prosperity", "All"],
    country: "UK",
    study_location: "Abroad",
    max_income_annual: null,
    min_gpa: 65,
    requires_disability: false,
    citizenship: "Indian",
    min_work_experience: 0,
    required_gender: "Any",
    deadline: "2027-10-17",
    application_url: "https://cscuk.fcdo.gov.uk/scholarships/commonwealth-masters-scholarships/",
    required_documents: ["3 Development Impact Essays", "2 Academic References", "Transcripts", "University Offer Letter"],
    application_effort_hours: 35,
    selection_criteria: "Academic merit + Development impact potential on home country",
    provider_type: "international",
    awards_per_year: 50,
    verified: true,
    notes: "For talented individuals who could not otherwise afford to study in the UK. Nominating agencies include MHRD India.",
  },
  {
    name: "GREAT Scholarships India (British Council UK)",
    provider: "British Council & UK Government",
    amount_value: 1050000,
    amount_currency: "INR",
    amount_string: "£10,000 (~₹10.5 lakh) towards tuition fee",
    cover_type: "partial",
    cover_details: "Tuition fee waiver of £10,000 for one-year postgraduate study in the UK",
    education_level: "postgrad",
    field_of_study: ["Engineering", "Law", "Business", "Art & Design", "Biosciences", "All"],
    country: "UK",
    study_location: "Abroad",
    max_income_annual: null,
    min_gpa: 60,
    requires_disability: false,
    citizenship: "Indian",
    min_work_experience: 0,
    required_gender: "Any",
    deadline: "2027-05-31",
    application_url: "https://www.britishcouncil.in/study-uk/scholarships/great-scholarships",
    required_documents: ["Offer Letter from participating UK University", "IELTS Scorecard", "Personal Statement"],
    application_effort_hours: 10,
    selection_criteria: "Academic performance + Statement of purpose",
    provider_type: "international",
    awards_per_year: 50,
    verified: true,
    notes: "Offered across 25+ participating UK universities exclusively for Indian passport holders.",
  },
  {
    name: "Australia Awards Scholarships for South Asia",
    provider: "Department of Foreign Affairs and Trade (DFAT Australia)",
    amount_value: 6000000,
    amount_currency: "INR",
    amount_string: "Full Tuition + Living Allowance (~$70,000 AUD)",
    cover_type: "full",
    cover_details: "Full tuition, return air travel, establishment allowance, contribution to living expenses (CLE), and OSHC health cover",
    education_level: "postgrad",
    field_of_study: ["Climate Change", "Agriculture", "Public Policy", "Health Security", "Infrastructure"],
    country: "Australia",
    study_location: "Abroad",
    max_income_annual: null,
    min_gpa: 65,
    requires_disability: false,
    citizenship: "Indian",
    min_work_experience: 2,
    required_gender: "Any",
    deadline: "2027-04-30",
    application_url: "https://www.dfat.gov.au/people-to-people/australia-awards/australia-awards-scholarships",
    required_documents: ["Degree Certificate", "IELTS (6.5+) / PTE", "Work Experience Proof (2+ years)", "Development Impact Plan"],
    application_effort_hours: 25,
    selection_criteria: "Academic merit + Leadership + Potential impact on national development",
    provider_type: "international",
    awards_per_year: 30,
    verified: true,
    notes: "Requires scholars to return to India for at least 2 years post-graduation to contribute to national growth.",
  },
  {
    name: "MEXT Japanese Government Scholarship for Research Students",
    provider: "Ministry of Education, Culture, Sports, Science and Tech (MEXT Japan)",
    amount_value: 1600000,
    amount_currency: "INR",
    amount_string: "Full Tuition + ¥143,000/month stipend (~₹16 lakh/year)",
    cover_type: "full",
    cover_details: "Complete exemption from entrance & tuition fees + monthly stipend + round-trip flight ticket to Japan",
    education_level: "postgrad",
    field_of_study: ["Engineering", "Robotics", "Japanese Studies", "Biotechnology", "Material Science", "All"],
    country: "Japan",
    study_location: "Abroad",
    max_income_annual: null,
    min_gpa: 70,
    requires_disability: false,
    citizenship: "Indian",
    min_work_experience: 0,
    required_gender: "Any",
    deadline: "2027-05-15",
    application_url: "https://www.in.emb-japan.go.jp/Education/Japanese_Government_Scholarships.html",
    required_documents: ["Field of Study and Research Plan", "Academic Transcripts", "Recommendation Letter", "Medical Certificate"],
    application_effort_hours: 30,
    selection_criteria: "Written examination (English/Japanese) + Embassy Interview",
    provider_type: "international",
    awards_per_year: 40,
    verified: true,
    notes: "Includes a 6-month preparatory Japanese language course upon arrival in Japan.",
  },
  {
    name: "JN Tata Endowment Loan Scholarship for Higher Education",
    provider: "Tata Trusts",
    amount_value: 1000000,
    amount_currency: "INR",
    amount_string: "₹1.0 lakh to ₹10.0 lakh loan scholarship",
    cover_type: "partial",
    cover_details: "Low-interest loan scholarship + gift bursary up to ₹7.5 lakh for top scholars",
    education_level: "postgrad",
    field_of_study: ["All"],
    country: "India",
    study_location: "Abroad",
    max_income_annual: null,
    min_gpa: 60,
    requires_disability: false,
    citizenship: "Indian",
    min_work_experience: 0,
    required_gender: "Any",
    deadline: "2027-03-21",
    application_url: "https://www.jntataendowment.org",
    required_documents: ["Graduation Marksheets", "Statement of Purpose", "Letter of Admission", "GRE/GMAT/IELTS Scorecard"],
    application_effort_hours: 15,
    selection_criteria: "Online Test + Technical Interview by subject experts",
    provider_type: "ngo",
    awards_per_year: 120,
    verified: true,
    notes: "Established in 1892 by Jamsetji Tata. Over 5,400 Indian scholars funded for study abroad.",
  },
];

module.exports = scholarships;
