/**
 * 25 realistic Indian + international scholarships seed data
 * Run: node scripts/seed.js
 */
const scholarships = [
  // ── GOVERNMENT / INDIA ──────────────────────────────────────────────────────
  {
    name: "National Scholarship Portal (NSP) — Post-Matric",
    provider: "Ministry of Education, India",
    amount_value: 120000,
    amount_currency: "INR",
    amount_string: "₹1.2 lakh/year",
    cover_type: "partial",
    cover_details: "Tuition fee reimbursement + maintenance allowance",
    education_level: "undergrad",
    field_of_study: ["All"],
    country: "India",
    study_location: "India",
    max_income_annual: 250000,
    min_gpa: 50,
    requires_disability: false,
    citizenship: "Indian",
    min_work_experience: 0,
    required_gender: "Any",
    deadline: "2027-11-30",
    application_url: "https://scholarships.gov.in",
    required_documents: ["10th Marksheet", "12th Marksheet", "Income Certificate", "Aadhaar Card", "Bank Passbook", "Caste Certificate (if applicable)", "Current Year Admission Proof"],
    application_effort_hours: 4,
    application_method: "Online",
    selection_criteria: "Merit-cum-means",
    provider_type: "government",
    provider_website: "https://scholarships.gov.in",
    awards_per_year: 50000,
    verified: true,
    notes: "Largest scholarship scheme in India. Apply before October each year.",
  },
  {
    name: "Prime Minister's Scholarship Scheme (PMSS)",
    provider: "Ministry of Home Affairs, India",
    amount_value: 36000,
    amount_currency: "INR",
    amount_string: "₹3,000/month (₹36,000/year)",
    cover_type: "partial",
    cover_details: "Monthly stipend for wards of ex-servicemen",
    education_level: "undergrad",
    field_of_study: ["Engineering", "Medicine", "Business", "Law", "Computer Science", "All"],
    country: "India",
    study_location: "India",
    max_income_annual: null,
    min_gpa: 60,
    requires_disability: false,
    citizenship: "Indian",
    min_work_experience: 0,
    required_gender: "Any",
    deadline: "2027-10-31",
    application_url: "https://ksb.gov.in/pmss.htm",
    required_documents: ["10th & 12th Marksheet", "Ex-serviceman Certificate", "Aadhaar Card", "Bank Account Details", "Admission Letter"],
    application_effort_hours: 5,
    application_method: "Online",
    selection_criteria: "Merit-based",
    provider_type: "government",
    awards_per_year: 5500,
    verified: true,
    notes: "For children and widows of ex-servicemen/ex-coast guard. ₹3,000/month for boys, ₹3,500/month for girls.",
  },
  {
    name: "INSPIRE Scholarship (SHE)",
    provider: "Department of Science & Technology, India",
    amount_value: 80000,
    amount_currency: "INR",
    amount_string: "₹80,000/year",
    cover_type: "partial",
    cover_details: "Annual scholarship + summer attachment grant",
    education_level: "undergrad",
    field_of_study: ["Science", "Computer Science", "Engineering"],
    country: "India",
    study_location: "India",
    max_income_annual: null,
    min_gpa: 80,
    requires_disability: false,
    citizenship: "Indian",
    min_work_experience: 0,
    required_gender: "Any",
    deadline: "2027-10-15",
    application_url: "https://online-inspire.gov.in",
    required_documents: ["12th Marksheet (top 1% proof)", "Admission Letter (BSc/BS/Int. MSc)", "Aadhaar Card", "Bank Details"],
    application_effort_hours: 4,
    application_method: "Online",
    selection_criteria: "Top 1% in Class 12 board exams",
    provider_type: "government",
    awards_per_year: 10000,
    competitive_ratio: "1:10",
    verified: true,
    notes: "Must be in top 1% of Class 12 and pursuing BSc/Int. MSc in natural/basic sciences.",
  },
  {
    name: "AICTE Pragati Scholarship for Girls",
    provider: "AICTE (All India Council for Technical Education)",
    amount_value: 50000,
    amount_currency: "INR",
    amount_string: "₹50,000/year + contingency",
    cover_type: "partial",
    cover_details: "Tuition fee + contingency grant of ₹2,000",
    education_level: "undergrad",
    field_of_study: ["Engineering", "Computer Science"],
    country: "India",
    study_location: "India",
    max_income_annual: 800000,
    min_gpa: 0,
    requires_disability: false,
    citizenship: "Indian",
    min_work_experience: 0,
    required_gender: "Female",
    deadline: "2027-11-15",
    application_url: "https://www.aicte-india.org/bureaus/boys_girls",
    required_documents: ["10th & 12th Marksheet", "Income Certificate", "Aadhaar Card", "Admission Letter", "Bank Passbook", "Self-declaration Form"],
    application_effort_hours: 4,
    application_method: "Online",
    selection_criteria: "Need-based + Merit",
    provider_type: "government",
    awards_per_year: 4000,
    competitive_ratio: "1:5",
    verified: true,
    notes: "For girls in AICTE-approved technical institutions. One girl per family.",
  },
  {
    name: "AICTE Saksham Scholarship for Specially Abled",
    provider: "AICTE",
    amount_value: 50000,
    amount_currency: "INR",
    amount_string: "₹50,000/year",
    cover_type: "partial",
    cover_details: "Tuition fee reimbursement + contingency allowance",
    education_level: "undergrad",
    field_of_study: ["Engineering", "Computer Science"],
    country: "India",
    study_location: "India",
    max_income_annual: 800000,
    min_gpa: 0,
    requires_disability: true,
    citizenship: "Indian",
    min_work_experience: 0,
    required_gender: "Any",
    deadline: "2027-11-15",
    application_url: "https://www.aicte-india.org",
    required_documents: ["Disability Certificate (≥40%)", "Income Certificate", "Aadhaar", "Admission Letter", "Marksheets"],
    application_effort_hours: 4,
    provider_type: "government",
    awards_per_year: 1000,
    verified: true,
    notes: "For students with ≥40% disability in AICTE-approved programmes.",
  },
  {
    name: "Central Sector Scheme (CSS) Scholarship",
    provider: "Ministry of Education, India",
    amount_value: 20000,
    amount_currency: "INR",
    amount_string: "₹10,000–20,000/year",
    cover_type: "partial",
    cover_details: "Annual scholarship for meritorious students from non-elite families",
    education_level: "undergrad",
    field_of_study: ["All"],
    country: "India",
    study_location: "India",
    max_income_annual: 450000,
    min_gpa: 80,
    requires_disability: false,
    citizenship: "Indian",
    min_work_experience: 0,
    required_gender: "Any",
    deadline: "2027-10-31",
    application_url: "https://scholarships.gov.in",
    required_documents: ["12th Marksheet", "Income Certificate", "Aadhaar", "Admission Letter", "Bank Details"],
    application_effort_hours: 3,
    provider_type: "government",
    awards_per_year: 82000,
    competitive_ratio: "1:3",
    verified: true,
    notes: "80,000+ awards per year. Among the most accessible central scholarships.",
  },
  // ── INTERNATIONAL ───────────────────────────────────────────────────────────
  {
    name: "Fulbright-Nehru Master's Fellowship",
    provider: "United States-India Educational Foundation (USIEF)",
    amount_value: 5000000,
    amount_currency: "INR",
    amount_string: "Full funding (~$50,000/year)",
    cover_type: "full",
    cover_details: "J-1 visa, tuition, living stipend, health insurance, travel",
    education_level: "postgrad",
    field_of_study: ["All"],
    country: "USA",
    study_location: "Abroad",
    max_income_annual: null,
    min_gpa: 65,
    requires_disability: false,
    citizenship: "Indian",
    min_work_experience: 2,
    required_gender: "Any",
    deadline: "2027-07-15",
    application_url: "https://www.usief.org.in/Fellowships/Fulbright-Nehru-Master-Fellowships.aspx",
    required_documents: ["Statement of Purpose (2000 words)", "3 Reference Letters", "Transcripts", "CV/Resume", "GRE/GMAT Score (optional)", "IELTS/TOEFL Score", "Passport"],
    application_effort_hours: 40,
    application_method: "Online",
    selection_criteria: "Merit-based + Leadership",
    provider_type: "international",
    competitive_ratio: "1:100",
    awards_per_year: 85,
    verified: true,
    notes: "Prestigious fully-funded scholarship for Master's at top US universities. 2+ years work experience required.",
  },
  {
    name: "Commonwealth Scholarship (UK)",
    provider: "Commonwealth Scholarship Commission (CSC)",
    amount_value: 6000000,
    amount_currency: "INR",
    amount_string: "Full funding (~£45,000)",
    cover_type: "full",
    cover_details: "Tuition, living allowance, airfare, thesis grant, study travel",
    education_level: "postgrad",
    field_of_study: ["All"],
    country: "UK",
    study_location: "Abroad",
    max_income_annual: null,
    min_gpa: 70,
    requires_disability: false,
    citizenship: "Indian",
    min_work_experience: 0,
    required_gender: "Any",
    deadline: "2027-10-31",
    application_url: "https://cscuk.fcdo.gov.uk/apply/scholarships/",
    required_documents: ["Research Proposal", "3 Academic References", "Transcripts", "CV", "IELTS (6.5+)", "Passport"],
    application_effort_hours: 35,
    selection_criteria: "Merit + Development impact",
    provider_type: "international",
    competitive_ratio: "1:150",
    awards_per_year: 30,
    verified: true,
    notes: "For Master's and PhD. Must demonstrate how you'll contribute to India's development.",
  },
  {
    name: "DAAD Scholarship (Germany)",
    provider: "German Academic Exchange Service (DAAD)",
    amount_value: 1200000,
    amount_currency: "INR",
    amount_string: "€934/month + travel + health insurance",
    cover_type: "full",
    cover_details: "Monthly stipend, travel allowance, health/accident/liability insurance",
    education_level: "postgrad",
    field_of_study: ["Engineering", "Computer Science", "Science", "All"],
    country: "Germany",
    study_location: "Abroad",
    max_income_annual: null,
    min_gpa: 70,
    requires_disability: false,
    citizenship: "Indian",
    min_work_experience: 2,
    required_gender: "Any",
    deadline: "2027-10-15",
    application_url: "https://www.daad.in/en/find-funding/",
    required_documents: ["Motivation Letter", "CV", "2 Reference Letters", "Transcripts", "German/English Language Certificate", "Research Proposal (for PhD)"],
    application_effort_hours: 20,
    selection_criteria: "Academic excellence + motivation",
    provider_type: "international",
    competitive_ratio: "1:50",
    awards_per_year: 200,
    verified: true,
    notes: "Multiple programmes. Many German universities have no tuition fees.",
  },
  {
    name: "Australia Awards Scholarship",
    provider: "Australian Government — DFAT",
    amount_value: 7500000,
    amount_currency: "INR",
    amount_string: "Full funding (AUD 80,000+/year)",
    cover_type: "full",
    cover_details: "Tuition, living allowance, health insurance, return airfare, introductory academic programme",
    education_level: "postgrad",
    field_of_study: ["All"],
    country: "Australia",
    study_location: "Abroad",
    max_income_annual: null,
    min_gpa: 65,
    requires_disability: false,
    citizenship: "Indian",
    min_work_experience: 2,
    required_gender: "Any",
    deadline: "2027-06-30",
    application_url: "https://www.australiaawards.gov.au/",
    required_documents: ["Personal Statement", "2 Professional References", "Transcripts", "IELTS (6.5+)", "CV", "Passport"],
    application_effort_hours: 25,
    selection_criteria: "Academic + Development impact",
    provider_type: "international",
    competitive_ratio: "1:80",
    awards_per_year: 50,
    verified: true,
    notes: "Prestigious scholarship for Master's at top Australian universities. Return to home country required after study.",
  },
  {
    name: "Erasmus Mundus Joint Master's",
    provider: "European Commission",
    amount_value: 4800000,
    amount_currency: "INR",
    amount_string: "€1,400/month + travel + tuition waiver",
    cover_type: "full",
    cover_details: "Monthly living allowance, travel grant, installation costs, tuition fee waiver",
    education_level: "postgrad",
    field_of_study: ["Computer Science", "Engineering", "Science", "Data Science", "All"],
    country: "Europe",
    study_location: "Abroad",
    max_income_annual: null,
    min_gpa: 70,
    requires_disability: false,
    citizenship: "Any",
    min_work_experience: 0,
    required_gender: "Any",
    deadline: "2027-01-15",
    application_url: "https://www.eacea.ec.europa.eu/scholarships/emjmd-catalogue",
    required_documents: ["Motivation Letter", "CV (Europass)", "2 Academic References", "Transcripts", "IELTS/TOEFL", "Language Certificates"],
    application_effort_hours: 25,
    selection_criteria: "Academic excellence",
    provider_type: "international",
    competitive_ratio: "1:60",
    awards_per_year: 2000,
    verified: true,
    notes: "Study in 2–3 European countries. Highly prestigious. Many programmes in English.",
  },
  {
    name: "Inlaks Scholarships",
    provider: "Inlaks Shivdasani Foundation",
    amount_value: 10000000,
    amount_currency: "INR",
    amount_string: "Up to $100,000 (for USA/UK/Europe)",
    cover_type: "full",
    cover_details: "Tuition, living expenses, economy airfare",
    education_level: "postgrad",
    field_of_study: ["All"],
    country: "USA",
    study_location: "Abroad",
    max_income_annual: null,
    min_gpa: 70,
    requires_disability: false,
    citizenship: "Indian",
    min_work_experience: 0,
    required_gender: "Any",
    deadline: "2027-03-31",
    application_url: "https://www.inlaksfoundation.org/scholarships/",
    required_documents: ["Personal Statement (1000 words)", "CV", "2 Referees", "Transcripts", "Proof of Admission to top university", "Passport"],
    application_effort_hours: 20,
    selection_criteria: "Academic + Leadership + India impact",
    provider_type: "ngo",
    competitive_ratio: "1:200",
    awards_per_year: 20,
    verified: true,
    notes: "Must have unconditional offer from top 50 university worldwide. Highly competitive.",
  },
  // ── CORPORATE / NGO ─────────────────────────────────────────────────────────
  {
    name: "Tata Scholarship — Cornell University",
    provider: "Tata Education and Development Trust",
    amount_value: 5800000,
    amount_currency: "INR",
    amount_string: "Full funding at Cornell (~$70,000/year)",
    cover_type: "full",
    cover_details: "Full tuition, living expenses, health insurance, books",
    education_level: "undergrad",
    field_of_study: ["All"],
    country: "USA",
    study_location: "Abroad",
    max_income_annual: 5000000,
    min_gpa: 90,
    requires_disability: false,
    citizenship: "Indian",
    min_work_experience: 0,
    required_gender: "Any",
    deadline: "2027-01-02",
    application_url: "https://financialaid.cornell.edu/types-aid/scholarships/tata-scholarship/",
    required_documents: ["Cornell Application", "Financial Aid Application (CSS Profile)", "10th & 12th Marksheets", "Letter of Recommendation (3)", "Essays", "SAT/ACT Score"],
    application_effort_hours: 50,
    selection_criteria: "Merit + Need",
    provider_type: "corporate",
    competitive_ratio: "1:500",
    awards_per_year: 20,
    verified: true,
    notes: "One of the most prestigious awards for Indian students at Cornell. Need-based with merit consideration.",
  },
  {
    name: "Reliance Foundation Scholarships",
    provider: "Reliance Foundation",
    amount_value: 600000,
    amount_currency: "INR",
    amount_string: "₹6 lakh total (₹2L/year for 3 years)",
    cover_type: "partial",
    cover_details: "Annual merit scholarship for undergraduate students",
    education_level: "undergrad",
    field_of_study: ["Engineering", "Computer Science", "Science", "Business"],
    country: "India",
    study_location: "India",
    max_income_annual: 1500000,
    min_gpa: 60,
    requires_disability: false,
    citizenship: "Indian",
    min_work_experience: 0,
    required_gender: "Any",
    deadline: "2027-04-30",
    application_url: "https://www.reliancefoundation.org/",
    required_documents: ["10th & 12th Marksheet", "Income Certificate", "Aadhaar", "Admission Letter", "Essay (500 words on social impact)"],
    application_effort_hours: 8,
    selection_criteria: "Merit + Need + Social impact potential",
    provider_type: "corporate",
    competitive_ratio: "1:30",
    awards_per_year: 5000,
    verified: true,
    notes: "Includes mentorship from Reliance professionals.",
  },
  {
    name: "Wipro Cares Scholarship",
    provider: "Wipro Foundation",
    amount_value: 150000,
    amount_currency: "INR",
    amount_string: "₹1.5 lakh/year",
    cover_type: "partial",
    cover_details: "Annual merit-cum-means scholarship for engineering students",
    education_level: "undergrad",
    field_of_study: ["Engineering", "Computer Science"],
    country: "India",
    study_location: "India",
    max_income_annual: 600000,
    min_gpa: 70,
    requires_disability: false,
    citizenship: "Indian",
    min_work_experience: 0,
    required_gender: "Any",
    deadline: "2027-08-31",
    application_url: "https://www.wipro.com/sustainability/wipro-cares/",
    required_documents: ["10th & 12th Marksheet", "Income Certificate", "Aadhaar", "College Admission Letter", "Bank Account"],
    application_effort_hours: 5,
    selection_criteria: "Merit + Need",
    provider_type: "corporate",
    competitive_ratio: "1:20",
    awards_per_year: 500,
    verified: true,
  },
  {
    name: "Aga Khan Foundation International Scholarship",
    provider: "Aga Khan Foundation",
    amount_value: 2500000,
    amount_currency: "INR",
    amount_string: "50% grant + 50% loan (~$25,000/year)",
    cover_type: "partial",
    cover_details: "Half grant, half interest-free loan covering tuition and living",
    education_level: "postgrad",
    field_of_study: ["All"],
    country: "USA",
    study_location: "Abroad",
    max_income_annual: 1000000,
    min_gpa: 65,
    requires_disability: false,
    citizenship: "Indian",
    min_work_experience: 2,
    required_gender: "Any",
    deadline: "2027-03-31",
    application_url: "https://www.akdn.org/our-agencies/aga-khan-foundation/social-development/education/higher-education",
    required_documents: ["Letter of Intent", "CV", "2 References", "Transcripts", "Proof of Admission", "Financial documents", "Essay on development goals"],
    application_effort_hours: 20,
    selection_criteria: "Need + Merit + Leadership",
    provider_type: "ngo",
    competitive_ratio: "1:60",
    awards_per_year: 30,
    verified: true,
    notes: "Primarily for students from developing nations pursuing postgrad abroad.",
  },
  {
    name: "Google Generation Scholarship",
    provider: "Google LLC",
    amount_value: 750000,
    amount_currency: "INR",
    amount_string: "$7,500 (~₹6.25 lakh)",
    cover_type: "partial",
    cover_details: "Annual cash scholarship + Google mentorship",
    education_level: "undergrad",
    field_of_study: ["Computer Science", "Data Science", "Engineering"],
    country: "India",
    study_location: "India",
    max_income_annual: null,
    min_gpa: 70,
    requires_disability: false,
    citizenship: "Any",
    min_work_experience: 0,
    required_gender: "Female",
    deadline: "2027-03-01",
    application_url: "https://buildyourfuture.withgoogle.com/scholarships/",
    required_documents: ["CV/Resume", "Transcripts", "Essay (600 words)", "1 Reference Letter"],
    application_effort_hours: 10,
    selection_criteria: "Merit + Demonstrated passion for tech",
    provider_type: "corporate",
    competitive_ratio: "1:100",
    awards_per_year: 30,
    verified: true,
    notes: "For women in Computer Science. Includes Google Summer of Code preference.",
  },
  {
    name: "KVPY Fellowship (Kishore Vaigyanik Protsahan Yojana)",
    provider: "Department of Science & Technology, India",
    amount_value: 96000,
    amount_currency: "INR",
    amount_string: "₹5,000–7,000/month fellowship",
    cover_type: "partial",
    cover_details: "Monthly fellowship during BSc/Int. MSc + annual contingency grant",
    education_level: "undergrad",
    field_of_study: ["Science", "Computer Science"],
    country: "India",
    study_location: "India",
    max_income_annual: null,
    min_gpa: 75,
    requires_disability: false,
    citizenship: "Indian",
    min_work_experience: 0,
    required_gender: "Any",
    deadline: "2027-08-31",
    application_url: "https://kvpy.iisc.ac.in/",
    required_documents: ["Class 10 & 12 Marksheets", "KVPY Aptitude Test Score", "Aadhaar", "Bank Details"],
    application_effort_hours: 10,
    selection_criteria: "KVPY Aptitude Test + Interview",
    provider_type: "government",
    awards_per_year: 1000,
    competitive_ratio: "1:50",
    verified: true,
    notes: "Prestigious fellowship. Must clear KVPY aptitude exam and interview.",
  },
  {
    name: "Maulana Azad National Fellowship (MANF)",
    provider: "Ministry of Minority Affairs, India",
    amount_value: 420000,
    amount_currency: "INR",
    amount_string: "₹31,000–35,000/month",
    cover_type: "full",
    cover_details: "JRF + SRF fellowship for PhD scholars from minority communities",
    education_level: "doctorate",
    field_of_study: ["All"],
    country: "India",
    study_location: "India",
    max_income_annual: null,
    min_gpa: 55,
    requires_disability: false,
    citizenship: "Indian",
    min_work_experience: 0,
    required_gender: "Any",
    deadline: "2027-09-30",
    application_url: "https://manf.ugc.ac.in/",
    required_documents: ["NET/JRF Scorecard", "Minority Community Certificate", "Aadhaar", "Admission Letter (PhD)", "Degree Certificates"],
    application_effort_hours: 10,
    provider_type: "government",
    awards_per_year: 756,
    verified: true,
    notes: "For Muslim, Christian, Sikh, Buddhist, Parsi, Jain minority community students pursuing PhD.",
  },
  {
    name: "Narotam Sekhsaria Scholarship",
    provider: "Narotam Sekhsaria Foundation",
    amount_value: 3000000,
    amount_currency: "INR",
    amount_string: "Up to ₹30 lakh (loan-based)",
    cover_type: "partial",
    cover_details: "Interest-free loan for postgraduate studies abroad at top universities",
    education_level: "postgrad",
    field_of_study: ["All"],
    country: "USA",
    study_location: "Abroad",
    max_income_annual: null,
    min_gpa: 70,
    requires_disability: false,
    citizenship: "Indian",
    min_work_experience: 0,
    required_gender: "Any",
    deadline: "2027-04-30",
    application_url: "https://www.nsf.org.in/scholarships",
    required_documents: ["Statement of Purpose", "CV", "2 Reference Letters", "Transcripts", "Proof of Admission (Top 50 world university)", "Essays"],
    application_effort_hours: 20,
    selection_criteria: "Academic merit + Interview",
    provider_type: "ngo",
    competitive_ratio: "1:100",
    awards_per_year: 40,
    verified: true,
    notes: "Interest-free loan repayable after employment. Highly competitive for top global universities.",
  },
  {
    name: "Sitaram Jindal Scholarship",
    provider: "Sitaram Jindal Foundation",
    amount_value: 24000,
    amount_currency: "INR",
    amount_string: "₹1,000–2,000/month",
    cover_type: "partial",
    cover_details: "Monthly stipend based on course and family income",
    education_level: "undergrad",
    field_of_study: ["All"],
    country: "India",
    study_location: "India",
    max_income_annual: 250000,
    min_gpa: 55,
    requires_disability: false,
    citizenship: "Indian",
    min_work_experience: 0,
    required_gender: "Any",
    deadline: "2027-07-31",
    application_url: "https://www.sitaramjindalfoundation.org/",
    required_documents: ["10th Marksheet", "Current Year Marksheet", "Income Certificate", "Aadhaar", "Admission Proof"],
    application_effort_hours: 3,
    selection_criteria: "Need-based",
    provider_type: "ngo",
    competitive_ratio: "1:5",
    awards_per_year: 10000,
    verified: true,
    notes: "One of the most accessible scholarships. Low income threshold but high award count.",
  },
  {
    name: "JN TATA Endowment Loan Scholarship",
    provider: "JN Tata Endowment",
    amount_value: 1000000,
    amount_currency: "INR",
    amount_string: "Up to ₹10 lakh (loan) + gift scholarship component",
    cover_type: "partial",
    cover_details: "Loan scholarship for postgraduate studies abroad; top performers get grant",
    education_level: "postgrad",
    field_of_study: ["All"],
    country: "USA",
    study_location: "Abroad",
    max_income_annual: null,
    min_gpa: 70,
    requires_disability: false,
    citizenship: "Indian",
    min_work_experience: 0,
    required_gender: "Any",
    deadline: "2027-03-15",
    application_url: "https://jntataendowment.org/",
    required_documents: ["Statement of Purpose", "Proof of Admission", "Academic Transcripts", "CV", "2 References", "Bank Statement"],
    application_effort_hours: 15,
    selection_criteria: "Merit + Interview",
    provider_type: "ngo",
    competitive_ratio: "1:40",
    awards_per_year: 150,
    verified: true,
    notes: "Loan converts to gift for scholars who return to India and contribute to development.",
  },
  {
    name: "Canada-ASEAN Scholarships (CAES)",
    provider: "Global Affairs Canada",
    amount_value: 3300000,
    amount_currency: "INR",
    amount_string: "CAD 50,000 full funding",
    cover_type: "full",
    cover_details: "Tuition, living, health insurance, return airfare, visa fees",
    education_level: "postgrad",
    field_of_study: ["All"],
    country: "Canada",
    study_location: "Abroad",
    max_income_annual: null,
    min_gpa: 65,
    requires_disability: false,
    citizenship: "Any",
    min_work_experience: 0,
    required_gender: "Any",
    deadline: "2027-02-28",
    application_url: "https://www.educanada.ca/scholarships-bourses/can/institutions/caes-pfac.aspx",
    required_documents: ["Motivation Letter", "CV", "Transcripts", "Language Proof (IELTS 6.5+)", "2 References", "Research Proposal"],
    application_effort_hours: 20,
    provider_type: "international",
    competitive_ratio: "1:80",
    awards_per_year: 100,
    verified: true,
    notes: "One-year Master's or short courses at Canadian universities. Includes ASEAN nations but open to Indians too.",
  },
  {
    name: "Rhodes Scholarship (India)",
    provider: "Rhodes Trust, Oxford",
    amount_value: 7500000,
    amount_currency: "INR",
    amount_string: "Full funding at Oxford (~£60,000/year)",
    cover_type: "full",
    cover_details: "Tuition fees, stipend, airfare, health insurance at Oxford",
    education_level: "postgrad",
    field_of_study: ["All"],
    country: "UK",
    study_location: "Abroad",
    max_income_annual: null,
    min_gpa: 85,
    requires_disability: false,
    citizenship: "Indian",
    min_work_experience: 0,
    required_gender: "Any",
    deadline: "2027-07-31",
    application_url: "https://www.rhodeshouse.ox.ac.uk/scholarships/the-rhodes-scholarship/",
    required_documents: ["Personal Statement", "4 Academic/Professional References", "Transcripts", "IELTS/TOEFL", "Leadership Evidence Portfolio", "Passport"],
    application_effort_hours: 60,
    selection_criteria: "Academic excellence + Leadership + Character",
    provider_type: "international",
    competitive_ratio: "1:1000",
    awards_per_year: 6,
    verified: true,
    notes: "Most prestigious scholarship in the world. Only 6 awarded from India per year. Must demonstrate outstanding academic AND leadership achievement.",
  },
  {
    name: "Chevening Scholarship (UK)",
    provider: "UK Government (FCDO)",
    amount_value: 5800000,
    amount_currency: "INR",
    amount_string: "Full funding (~£45,000)",
    cover_type: "full",
    cover_details: "Tuition, monthly living allowance, economy travel, visa fees",
    education_level: "postgrad",
    field_of_study: ["All"],
    country: "UK",
    study_location: "Abroad",
    max_income_annual: null,
    min_gpa: 65,
    requires_disability: false,
    citizenship: "Indian",
    min_work_experience: 2,
    required_gender: "Any",
    deadline: "2027-11-05",
    application_url: "https://www.chevening.org/apply/",
    required_documents: ["Personal Statement (4 essays)", "2 Professional References", "Transcripts", "IELTS (6.5+)", "CV", "Passport"],
    application_effort_hours: 30,
    selection_criteria: "Leadership + Academic merit + Impact potential",
    provider_type: "international",
    competitive_ratio: "1:200",
    awards_per_year: 70,
    verified: true,
    notes: "For future leaders. Requires 2 years work experience. Apply Nov–Nov cycle.",
  },
];

module.exports = scholarships;
